### ISSUE TITLE
Questionable Exception handling in LoggerNode.

### ISSUE THREAD

**Issue by zolyfarkas** [dmlloyd/jboss-logmanager-embedded#1]
I was not able to find the top level project this is being forked from, this should probably be reported there.

There is some questionable Exception handling in LoggerNode:

https://github.com/dmlloyd/jboss-logmanager-embedded/blob/master/src/main/java/org/jboss/logmanager/LoggerNode.java#L320

```     
        try {
            handler.publish(record);
        } catch (VirtualMachineError e) {
            throw e;
        } catch (Throwable t) {
            // todo - error handler
        }
```

This issue shows up when trying out quarkus.
Our unit tests throw an AssertionError if an unasserted LOG above warning is being made. ([spf4j-test](http://www.spf4j.org/spf4j-slf4j-test/index.html))
This exception handling interferes with that.

I recommend removing this exception handling...

**Comment by dmlloyd** [comment]
The reason the exception handling exists is because historically, badly-behaved handlers have caused cascading failures for users.  That said, there's really no reason why this hasn't been updated to push through the error manager; it was simply missed.  Then if you wanted to catch a deliberately-thrown exception, you could use a custom error manager to do so.
